### ISSUE TITLE
20 ft intervals for contour lines

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/landmapper#43]
make countour line resoultion helpful at zoom. this will mean approx 20ft intervals for countour lines.

- [ ] test resolution
- [ ] limit zoom beyond good resolution

**Comment by sloreno** [comment]
If 20 ft is too intense, we can do 40.

**Comment by pollardld** [comment]
10 ft  
https://services.nationalmap.gov/arcgis/rest/services/USGSTopoLarge/MapServer/35
