### ISSUE TITLE
Search Bar Offsetting Draw Pointer

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/landmapper#48]
This may be resolved by #47 if the map content ends up sliding under the header (z axis) rather than starting below it (y axis).

The drawing point is clearly making assumptions about where the map is on the screen, and the map has shifted several pixels upwards when the search bar (lower nav) disappears. If you make it reappear, pushing the map back down, the pointer lines up again.

Ideally, every bit of interaction should float above the map - it avoids issues like this, and makes no difference to the users.

**Comment by pollardld** [comment]
now floating above map
