### ISSUE TITLE
Help Bubble styles are suddenly all screwy

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/landmapper#53]
Since latest push, help bubbles appear mostly off-screen. Also the LM Head buttons seem duplicated during the process.

**Comment by rhodges** [comment]
Screenshot to be less ambiguous:
![bubble_error](https://user-images.githubusercontent.com/526505/28495328-ee8e84a8-6efd-11e7-97d4-e5de5c88c415.png)

**Comment by pollardld** [comment]
Fix in latest commit
