### ISSUE TITLE
both CMS and Django links for admin take me to Django?

### ISSUE THREAD

**Issue by d-diaz** [Ecotrust/landmapper#69]
Django URL target is http://landmapper.ecotrust.org/admin/
CMS URL target is http://landmapper.ecotrust.org/admin

Are these supposed to be different?

**Comment by rhodges** [comment]
@d-diaz No, they both go to the same place. Traditionally Marine-Planner is tied to a comprehensive CMS tool called Wagtail, but it was not necessary to incorporate into this tool. Removing the button would take extra time, and the button only shows to admins (You, Sara, David P., and I) so we decided not to proceed.
